### ISSUE TITLE
Epic: Judging Flow

### ISSUE THREAD

**Issue by couchoud** [openair-collective/Carbon-Forming#28]
## Expected Behavior

An Admin should be rank projects after a competition has ended

CompetitionList:

- [x] Disable and update 'Enter Competition' button so that it reads "Judging in Progress"
- [x] Admin Only: Add "Enter Results" button to completed competition list item that links to CompetitionShow 'Results'.

![Screen Shot 2022-10-18 at 11 12 41 AM](https://user-images.githubusercontent.com/71439/196472379-c659afa2-bc2b-45e4-be74-b9318dbd19c0.png)

CompetitionForm:

- [x] Add metric title property to Competition
- [x] Add metric value property to Competition
- [x] Update schema in [wiki](https://github.com/openair-collective/Carbon-Forming/wiki/Schema)

![Screen Shot 2022-10-25 at 9 31 28 AM](https://user-images.githubusercontent.com/71439/197787786-af041bef-b0a7-459a-9c6c-62fd0b8f8041.png)

CompetitionShow:

- [x] Add Results tab - Disable the tab until the competition has finished 
- [x] Results View Admin: Admin should be able to "Enter Results"
- [x] Admin Only: Add "Announce Results" Button when projects have been ranked
- [x] Results View User: User should see ranked projects as a leaderboard

**Enter Results**

![Screen Shot 2022-10-25 at 9 34 53 AM](https://user-images.githubusercontent.com/71439/197788477-c308b65c-913e-429d-8b49-f9c6097b263d.png)

**Ranked Projects Leaderboard:**

![Screen Shot 2022-10-25 at 9 35 23 AM](https://user-images.githubusercontent.com/71439/197788591-725a1f9e-e3fa-4b92-9c7d-b39a33233769.png)

**Announce Results:**

![Screen Shot 2022-10-18 at 11 17 15 AM](https://user-images.githubusercontent.com/71439/196473089-180ff56e-c2a1-441e-ae0e-d2d34b319262.png)

**Comment by couchoud** [comment]
Addressed in PR #48
