### ISSUE TITLE
Epic: Delete Flows

### ISSUE THREAD

**Issue by couchoud** [openair-collective/Carbon-Forming#37]
## Expected Behavior

A User should be able to delete their teams and projects. Deleting a Team will also delete child Projects.

An Admin should be able to delete Competitions. Deleting a Competition SHOULD NOT delete child projects

---

1. User clicks "Delete" button for target Team/Project/Competition model
2. User is prompted to confirm deletion
3. Model is deleted and User is redirected to model list

Sample Prompt:

![Screen Shot 2022-10-20 at 9 34 21 AM](https://user-images.githubusercontent.com/71439/196964133-cb7acdca-bce7-4032-930e-fc41357018af.png)

---

Todos:

- [x] Add delete workflow for a Team
- [x] Add delete workflow for a Project
- [x] Add delete workflow for a Competition

**Comment by couchoud** [comment]
Fixed in PR #69
